name: openpay_bbva
description: This is a package that uses the Openpay iOS and Openpay Android libraries to tokenize payments through the BBVA Openpay Platform.
version: 1.0.4
homepage: https://github.com/FMarcelFC

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  openpay: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.fortune.openpay_bbva
        pluginClass: OpenpayBbvaPlugin
      ios:
        pluginClass: OpenpayBbvaPlugin
      web:
        dartPluginClass: OpenpayBBVA
        fileName: openpay_bbva.dart
      


