name: openpay_bbva
description: This is a package that uses the Openpay iOS and Openpay Android libraries to tokenize payments through the BBVA Openpay Platform.
version: 1.0.0
homepage: https://github.com/FMarcelFC

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  openpay: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  plugin:
    platforms:
      android:
        package: com.fortune.openpay_bbva
        pluginClass: OpenpayBBVAPlugin
      ios:
        pluginClass: OpenpayBBVAPlugin
      web:
        dartPluginClass: OpenpayBBVA
        fileName: openpay_bbva.dart
      macos: 
        dartPluginClass: OpenpayBBVA
      windows: 
        dartPluginClass: OpenpayBBVA

