import 'package:flutter/foundation.dart' show kIsWeb, defaultTargetPlatform, TargetPlatform;
import 'package:flutter/services.dart';

import '../enums/country.dart';
import '../http/openpay_api.dart';
import '../models/card_information.dart';

/// Main entry point for the Openpay BBVA Flutter plugin.
///
/// Extends [OpenpayApi] to add native platform support (iOS / Android) for
/// retrieving the **Device Session ID**, which is required by Openpay's
/// anti-fraud system.
///
/// Card tokenization via [getCardToken] works on all platforms through HTTP.
///
/// ## Example
///
/// ```dart
/// final openpay = OpenpayBBVA(
///   merchantId: 'YOUR_MERCHANT_ID',
///   publicApiKey: 'YOUR_PUBLIC_API_KEY',
///   productionMode: false,
///   country: Country.MX,
/// );
///
/// // Retrieve the device session ID (mobile only)
/// final deviceId = await openpay.getDeviceID();
///
/// // Tokenize a card on any platform
/// final token = await openpay.getCardToken(
///   CardInformation(
///     holderName: 'John Doe',
///     cardNumber: '4111111111111111',
///     expirationMonth: '12',
///     expirationYear: '25',
///     cvv2: '123',
///   ),
/// );
/// ```
class OpenpayBBVA extends OpenpayApi {
  /// Creates an [OpenpayBBVA] instance.
  ///
  /// Both [merchantId] and [publicApiKey] are obtained from the dashboard of
  /// your account at [https://www.openpay.mx](https://www.openpay.mx).
  ///
  /// - [merchantId]: Your unique merchant identifier.
  /// - [publicApiKey]: Your public API key (never use the private key here).
  /// - [productionMode]: Set to `true` to use the production environment.
  ///   Defaults to `false` (sandbox mode).
  /// - [country]: The country associated with your Openpay account.
  ///   Defaults to [Country.MX].
  OpenpayBBVA({
    required String merchantId,
    required String publicApiKey,
    bool productionMode = false,
    Country country = Country.MX,
  }) : super(
          merchantId: merchantId,
          publicApiKey: publicApiKey,
          isSandboxMode: !productionMode,
          country: country,
        );

  /// Returns the **Device Session ID** generated by the Openpay native SDK.
  ///
  /// This identifier is used by Openpay's anti-fraud system to associate a
  /// transaction with the physical device that initiated it. It must be sent
  /// alongside the card token when creating a charge.
  ///
  /// > **Platform support**: iOS and Android only.
  /// > Returns `null` on Web, Windows, macOS, and Linux.
  ///
  /// Throws an [Exception] if the native SDK returns a [PlatformException].
  ///
  /// ```dart
  /// final deviceId = await openpay.getDeviceID();
  /// if (deviceId != null) {
  ///   // Use deviceId when creating a charge
  /// }
  /// ```
  Future<String?> getDeviceID() async {
    // kIsWeb must be checked before accessing dart:io Platform,
    // because dart:io is not available on Web.
    if (kIsWeb || (defaultTargetPlatform != TargetPlatform.iOS && defaultTargetPlatform != TargetPlatform.android)) {
      return null;
    }
    try {
      final deviceID = await _methodChannel.invokeMethod<String>(
        'getDeviceId',
        {
          'MERCHANT_ID': merchantId,
          'API_KEY': publicApiKey,
          'productionMode': !isSandboxMode,
          'country': country.name,
        },
      );
      return deviceID;
    } on PlatformException catch (e) {
      throw Exception(e.message);
    }
  }

  /// Tokenizes a card and returns the resulting **card token** as a [String].
  ///
  /// The token can be used to create charges through the Openpay API without
  /// transmitting sensitive card data from your server. Works on all platforms.
  ///
  /// Throws an [OpenpayExceptionError] if the API returns an error response.
  ///
  /// ```dart
  /// final token = await openpay.getCardToken(
  ///   CardInformation(
  ///     holderName: 'John Doe',
  ///     cardNumber: '4111111111111111',
  ///     expirationMonth: '12',
  ///     expirationYear: '25',
  ///     cvv2: '123',
  ///   ),
  /// );
  /// ```
  Future<String> getCardToken(CardInformation card) async =>
      (await getToken(card)).id;

  /// The [MethodChannel] used to communicate with the native Openpay SDK
  /// on iOS and Android.
  static const _methodChannel = MethodChannel('openpay_bbva');
}
